#********************************************************************************
# This file contains project specific environment variables
# For details see https://github.com/devonfw/ide/wiki/configuration
#********************************************************************************

# Uncomment the following line to get the legacy default config back for the settings
#SETTINGS_PATH=${DEVON_IDE_HOME}/workspaces/main/development/settings

# This following disables legacy support for devonfw-ide configuration templates in IDE workspace folders.
# Here, it is disabled since this is the configuration ready for IDEasy that does not need legacy support.
# The new variable syntax in workspace template files is $[<variable-name>]
# If legacy support is enabled, then also ${<variable-name>} is supported additionally.
# However, this often clashes with the variable syntax used by IDEs like Eclipse or IntelliJ.
# Therefore it causes some log-spam for variables that could not be resolved and could also lead to problems
# in edge-cases where variables get resolved by IDEasy that should actually remain as is and only be resolved
# by the actual IDE itself.
# Please note that in ide.properties/devon.properties files the syntax is still ${<variable-name>}
IDE_VARIABLE_SYNTAX_LEGACY_SUPPORT_ENABLED=false

# LTS versions
DOTNET_VERSION=6*
JAVA_VERSION=25*
NODE_VERSION=v26*
PYTHON_VERSION=3.11*
GRAALVM_VERSION=23.0.2
GRAALVM_EDITION=community
IDE_MIN_VERSION=2025.06.001
INTELLIJ_VERSION=2026.1.3

IDE_TOOLS=mvn, npm
CREATE_START_SCRIPTS=intellij
